# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'
footer: 'ğ“ğ“· ğ”‚ğ“¸ğ“¾ğ“» ğ“¶ğ“ªğ“»ğ“´'

theme: jekyll-theme-dinky

#style: dark # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
